#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# Displays the username, user id, and home directory path for user

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
