#!/usr/bin/env bash
# Bash script displays content of the file /etc/passwd,using the while loop + IFS

while IFS=':' read -r USERNAME PASSWORD USERID GROUP_ID USERIDINFO HOME_DIRECTORY COMMANDSHELL; do
  echo "The user $USERNAME is part of the $GROUP_ID gang,"\
  "lives in $HOME_DIRECTORY and rides $COMMANDSHELL."\
  "$USERID's place is protected by the passcode $PASSWORD,"\
  "more info about the user here: $USERIDINFO"
done < "/etc/passwd"
