#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

num=0
while [ $num -lt 10 ]
do
	if [ $num -eq 3 ]
then
		echo "bad luck"

	elif [ $num -eq 7 ]
then
		echo "good luck"

	else
		echo "Best School"

	fi
	(( num++ ))
done
