#!/usr/bin/env bash
#Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

for file in *; do
    # Check if the file is a regular file (not a directory)
    if [ -f "$file" ]; then
        # Extract the part of the name after the first dash
        name_part=$(echo "$file" | cut -d'-' -f2-)
        echo "$name_part"
    fi
done
